modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="everlaartifacts"
version="2.0.01.20.1"
displayName="EverlaArtifacts"
displayURL="https://space.bilibili.com/485238732?spm_id_from=333.1007.0.0"
logoFile="logo.png"
credits="fumofumo, fumofumofumo"
authors="EverlaPrismerAya"
description="Some items and other things from my old mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.everlaartifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration